### PR TITLE
Add composer.json.

### PR DESCRIPTION
**Pull request by mstenta**
This just adds a simple composer.json to allow this module to be pulled in via Composer.

### CODE REVIEW

**Comment by Farmer-Eds-Shed** [comment]
@mstenta, I hit merge on this but I just realized this has a dependency 
composer require 'drupal/google_api_client:^4.2'
I presume it should be included in the composer.json also?

**Comment by mstenta** [comment]
Ah good catch @Farmer-Eds-Shed! Yes that should be included.

**Comment by mstenta** [comment]
If it depends on that to function then it should also be listed in the `dependencies` in `farm_withdrawal.info.yml` so it gets enabled with this module.

**Comment by mstenta** [comment]
Another option might be to make that bit optional within this module.

**Comment by Farmer-Eds-Shed** [comment]
> Another option might be to make that bit optional within this module.

Yes probably should........
But then we would need to develop the means in farmOS to to create a Flag at the start of the withdrawal period and remove it at the end, using the calendar was my workaround.

**Pull request merged**
